config/routes.rb
Rails.application.routes.draw do
  root 'session#new'


  get 'session/new'

  get 'session/create'
  get 'session/destroy'

  get "/login" => "session#new"
  post "/login" => "session#create"
  delete "/login" => "session#destroy"

  get "/solutions/trial" => "solutions#trial"
  resources :solutions

  resources :challenges
  resources :test_pairs
  resources :users
  resources :comments
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :solutions
  has_many :challenges
  has_many :comments
  validates :email, presence: true, uniqueness: true
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find params[:id]
  end

  def index
    @user = User.all
  end

  def new
    @user = User.new
  end

  def create
    user = User.create user_params
    if user.persisted?
      session[:user_id] = user.id
      redirect_to user_path user.id
    else
      flash[:errors] = user.errors.full_messages
      redirect_to new_user_path
    end
  end

  def edit
      @comment = Comment.find params[:id]
      unless @comment.user == @current_user  #check if user id associated with comment, is the same as the currnet user
        flash[:error] = "You must be the owner of this comment to edit."
        redirect_to conflict_path(@comment.conflict_id)
      end

    end

    def update
      @comment = Comment.find params[:id]  #find comment
      @comment.update comment:params[:comment][:comment ]  #actual comment is a hash within a hash
      redirect_to conflict_path(@comment.conflict_id)

    end

  def destroy
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
  <hr>
    <h4 class ="createacc">Create New Account</h4>
  <%if flash[:errors].present? %>
  <strong>Please correct the following errors</strong>
  <ol>
  <%= flash[:errors].each do |e| %>
  <li><%= e %></li>
  <% end %>
  </ol>
<% end %>
    <%= form_for @user do |f| %>

    <div class = "jumbotron jumbotron-signup">
    <div class = "form-signup">
    <%= f.label :name %>
    <br>
    <%= f.text_field :name, class: "form-control" %>
    <br><br>
    <%= f.label :email %>
    <br>
    <%= f.email_field :email, class:"form-control" %>
    <br><br>
    <%= f.label :password %>
    <br>
    <%= f.password_field :password, class: "form-control" %>
    <br><br>
    <%= f.label :password_confirmation %>
    <br>
    <%= f.password_field :password_conirmation, class: "form-control"%>
    <br>
    <br>
    <%= f.submit class: "btn btn-primary btn-lg" %>




  <% end %>

  </div>
  </div>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<h1>Successful login</h1>


<h3>Your challenges</h3>

app/views/users/new.html.erb
<div class="CreateAcc"><%= render partial: 'form' %>
</div>

app/views/users/show.html.erb
<div class ="wrapper">
  <div class ="left-Col">
    <h3 class="yoursol"><strong>View Your solutions</strong></h3>

    <div class="card border-primary mb-3" style="max-width: 90rem;">
      <div class="card-header">
        <p class = "link btn btn-primary btn-lg btn-block">
          <%= link_to 'Start new challenge', challenges_path, class:"alink"	 %>
        </p>
      </div>
      <div class="card-body">
        <h5 class="card-title"></h5>
        <p class="card-text">
          <ul class="yoursolutions">
            <% @user.solutions.each do |solution| %>
              <li>
                <h3><%= link_to "#{solution.challenge.name}", solution_path(solution.id)  %>
                </h3>
                Created
                <%= time_ago_in_words(solution.created_at) %>
              </li>
            <% end %>
          </ul>
        </p>
      </div>
    </div>
  </div>

  <div class="right-Col">
    <h3 class="chal"><strong>Your created challenges</strong></h3>

    <div class="card border-primary mb-3" style="max-width: 50rem;">
      <div class="card-header">
            <p class="link btn btn-primary btn-lg btn-block">
                <%= link_to      'Create new challenge', new_challenge_path, class:"alink" %>
            </p>
      </div>
      <div class="card-body">
         <p class="card-text">
          <ul class="yourchallenge">
            <% @user.challenges.each do |challenge| %>
              <li>
                  <h3><%= link_to challenge.name, challenge_path(challenge.id) %>  </h3> created
                <%= time_ago_in_words(challenge.created_at) %>
               </li>
            <% end %>
          </ul>
        </p>
      </div>
    </div>
  </div>
</div>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>