config/routes.rb
Rails.application.routes.draw do
  root 'session#new'


  get 'session/new'

  get 'session/create'
  get 'session/destroy'

  get "/login" => "session#new"
  post "/login" => "session#create"
  delete "/login" => "session#destroy"

  get "/solutions/trial" => "solutions#trial"
  resources :solutions

  resources :challenges
  resources :test_pairs
  resources :users
  resources :comments
end

app/models/challenge.rb
class Challenge < ApplicationRecord
  belongs_to :user, optional: true
  has_many :solutions
  has_many :test_pairs
  validates :name, presence: true
end

app/controllers/challenges_controller.rb
class ChallengesController < ApplicationController

  skip_before_action :verify_authenticity_token

  def new
    @challenge = Challenge.new
    @challenge.user_id = @current_user.id
  end

  def create
    challenge = Challenge.create(challenge_params)
    challenge.user_id = @current_user.id
    challenge.save
    redirect_to challenge_path(challenge.id)
  end

  def index
    @challenges = Challenge.all.reverse
    @random = get_random(@challenges)
  end

  def show
    @challenge = Challenge.find params[:id]
    @next = next_chall(Challenge.all, @challenge)
    @solved = @challenge.solutions.map  { |x| x.user_id }
    if @current_user.present?
      @solutions = @current_user.solutions
      @solution = show_current_solution(@solutions, params[:id])
    end
    if @challenge.solutions.length > 0
      solved_rate = @challenge.solutions.map  { |x| x.score }
      @solved_rate = (solved_rate.reduce(:+))/solved_rate.length
      @difficulty = difficulty_rating(@solved_rate)
    end
  end

  def edit
    @challenge = Challenge.find params[:id]
  end

  def update
    @challenge = Challenge.find params[:id]
    @challenge.save
    if @challenge.update(challenge_params)
      redirect_to( challenge_path( @challenge.id ) )
    else
      flash[:errors] = @challenge.errors.full_messages
      render :edit
    end
  end

  def destroy
    challenge = Challenge.find params[:id]
    challenge.destroy
    redirect_to challenges_path
  end

  private
  def challenge_params
    params.require(:challenge).permit(:name, :description, :user_id)
  end

  def get_random(arr)
    arr.sample
  end

  def next_chall (arr, challenge)
    chall_index = arr.index(challenge)
    if challenge == arr.last
      arr.first
    else
      arr[chall_index + 1]
    end
  end

  def show_current_solution (arr, num)
    arr.each do |element|
      if element.id == num
        element
      end
    end
  end

  def difficulty_rating(rating)
    rate = rating.to_i
    case
    when rate >= 75
      "Easy"
    when rate < 75.0 && rate >= 50
      "Medium"
    when rate < 50 && rate >= 25
      "Hard"
    when rate < 25
      "Diabolical"
    end
  end
end

app/helpers/challenges_helper.rb
module ChallengesHelper
end

app/views/challenges/_form.html.erb
<% if flash[:errors].present? %>
  <strong>Please correct the following errors in the form:</strong>
  <ol>
    <% flash[:errors].each do |error| %>
      <li>
        <%= error %>
      </li>
    <% end %>
  </ol>
<% end %>

<div class="form-group">

  <%= form_for @challenge do |f| %>
  <%= f.label :name, class: "name" %> <br>
  <%= f.text_field :name, class: "yes form-control  " %>
  <br>
  <br>
  <br>
  <%= f.label :description, class:"des" %> <br>
  <%= f.text_area :description, class: "form-control, formDesc" %>
  <br>
  <br>
  <%= f.submit class: "btn-primary btn-lg" %>
  <% end %>

</div>

app/views/challenges/create.html.erb
<h1>Challenges#create</h1>
<p>Find me in app/views/challenges/create.html.erb</p>

app/views/challenges/destroy.html.erb
<h1>Challenges#destroy</h1>
<p>Find me in app/views/challenges/destroy.html.erb</p>

app/views/challenges/edit.html.erb
<h2>Edit Your Challenge: <%= @challenge.name %></h2>

<%= render partial: 'form' %>

app/views/challenges/index.html.erb
<div class= buttons >
  <%= link_to "Random Challenge", challenge_path(@random), class:"btn btn-primary" %>
  <% if @current_user.present? %>
    <%= link_to 'Add New Challenge', new_challenge_path, class:"btn btn-primary" %>
  <% end %>
</div>
<br>
<div class="border card border-primary mb-3" style="max-width: 20rem;">
  <div class="card-header">Start a challenge!</div>
  <div class="card-body">
    <h4 class="card-title">All challenges</h4>
    <p class="card-text">
      <% @challenges.each do |challenge| %>
        <li class="challengeName">
          <%= link_to challenge.name, challenge_path(challenge.id)  %>
        </li>
      <% end %>
    </p>
  </div>
</div>

app/views/challenges/new.html.erb
<h2>Add A Challenge</h2>

<%= render partial: 'form' %>

app/views/challenges/show.html.erb
<div class="challContainer">
  <div class="challGridItem1">

    <div class="card border-primary   mb-3" style="max-width: 20rem;">
          <div class="card-header">
            <h3><strong>Challange name:</strong></h3><%= @challenge.name%><br><%= link_to "BACK TO CHALLENGES", challenges_path, class: "btn btn-primary" %>

          </div>

          <div class="card-body">
            <h4 class="card-title">
            </h4>
            <p class="card-text">

                <% if @solutions == nil %>
                  <%= link_to "Start A Solution For This Challenge", new_solution_path(params: {id: @challenge.id}) %> <br>
                <% else %>
                  <% if (!@solved.include?(@current_user.id)) %>
                    <%= link_to "Start A Solution For This Challenge", new_solution_path(params: {id: @challenge.id}) %> <br>
                  <% else %>
                    <p><%= link_to "View Your Solution", solution_path(@solution[0].id) %></p>
                  <% end %>
                <% end %>
                OR <br>
                <%= link_to "Go To Next Challenge", challenge_path((@next)) %>
                <br>
                <br>
                <p><strong>Description:</strong> <%= @challenge.description %></p>
                <p><strong>Difficulty:</strong>
                  <% if !@difficulty %>
                  Challenge Not Yet Attempted
                  <% else %>
                    <%= @difficulty %>
                  <% end %>
                </p>
                <p><strong>Completion Rate:</strong>
                  <% if !@solved_rate %>
                    Challenge Not Yet Attempted
                  <% else %>
                    <%= @solved_rate %>%
                  <% end %>
                </p>
                <p><strong>Created By:</strong> <%= @challenge.user.name %>


                <br>
                <br>
                <br>
                <br>
                <% if @current_user.present? %>
                  <% if @current_user.challenges.include?(@challenge) %>
                    <%= link_to 'Edit Challenge', edit_challenge_path(@challenge.id) %><br>
                    <%= link_to 'Delete Challenge', challenge_path(@challenge.id), method: 'delete' %><br>
                  <% end %>
                <% end %>

                <br></p>
          </div>
        </div>
  </div>







  <div class="challGridItem2">

  <div class="card border-primary mb-3" style="max-width: 20rem;">
  <div class="card-header">
     <h2><strong>Test Pairs</strong></h2><% if @current_user.present? %>
         <% if @current_user.challenges.include?(@challenge) %>
           <%= link_to 'Add A Test Pair', new_test_pair_path(params: {id: @challenge.id}), class: "btn btn-primary" %><br>
         <% end %>
       <% end %>
  </div>
  <div class="card-body">
    <p class="card-text test">
      <ul>
        <% @challenge.test_pairs.each do |test_pair|%>
          <li>
            <strong>Input:</strong> <%= test_pair.input %> <br>
            <strong>Output:</strong> <%= test_pair.output %> <br>
            <% if @current_user.present? %>
              <% if @current_user.challenges.include?(@challenge) %>
                <%= link_to 'Edit Test Pair', edit_test_pair_path(test_pair.id) %><br>
                <%= link_to 'Delete Test Pair', test_pair_path(test_pair.id), method: 'delete' %>
              <% end %>
            <% end %>
            <br>
            <br>
          </li>
        <% end %>
      </ul>
    </p>
  </div>
    </div>
  </div>

  <div class="challGridItem3">

    <div class="card border-primary mb-3" style="max-width: 20rem;">
      <div class="card-header">                                                               <h2><strong>Solutions</strong></h2>
      </div>
      <div class="card-body">
        <h4 class="card-title">
          <button class="btn btn-primary showSolutionButton">Click Here To Show Solutions</button>
        </h4>
        <p class="card-text">
          <div class="hiddenSolutions">
          <% if @challenge.solutions.length > 0 %>
            <ul>
              <% @challenge.solutions.each do |solution| %>
                <li>
                  <strong>User</strong> <%= link_to solution.user.name, solution_path(solution.id) %><br>
                  <strong>Solution</strong> <%= solution.code %><br><br>
                </li>
              <% end %>
            </ul>
          <% else %>
            <p>There are no Solutions to this challenge. Lead the way and <%= link_to "Start A Solution For This Challenge", new_solution_path(params: {id: @challenge.id}) %> </p>
          <% end %>
        </p>
      </div>
    </div>
  </div>
</div>

app/views/challenges/update.html.erb
<h1>Challenges#update</h1>
<p>Find me in app/views/challenges/update.html.erb</p>