config/routes.rb
Rails.application.routes.draw do
  root 'session#new'


  get 'session/new'

  get 'session/create'
  get 'session/destroy'

  get "/login" => "session#new"
  post "/login" => "session#create"
  delete "/login" => "session#destroy"

  get "/solutions/trial" => "solutions#trial"
  resources :solutions

  resources :challenges
  resources :test_pairs
  resources :users
  resources :comments
end

app/models/solution.rb
class Solution < ApplicationRecord
  belongs_to :user, optional: true
  has_many :comments
  belongs_to :challenge, optional: true

end

app/controllers/solutions_controller.rb
class SolutionsController < ApplicationController

  skip_before_action :verify_authenticity_token


  def new
    @challenge = Challenge.find params[:id]
    if @current_user.present?
      @solution = Solution.create(
        challenge_id: @challenge.id,
        user_id: @current_user.id,
        score: 0
      )
      redirect_to edit_solution_path @solution.id
    else
      redirect_to solutions_trial_path(params: {id: @challenge.id})
    end
  end

  def create
    solution = Solution.new solution_params
    if @current_user.present?
      solution.user_id = @current_user.id #should be 'current user'
      solution.save
      redirect_to controller: 'solutions', action: 'show', id: solution.id
    else
      redirect_back fallback_location: request.referrer
    end
  end

  def edit
    @solution = Solution.find(params[:id])
    @challenge = Challenge.find(@solution.challenge_id)
    @data = getData(@challenge).to_json.html_safe
  end

  def trial
    @challenge = Challenge.find(params[:id])
    @data = getData(@challenge).to_json.html_safe
  end

  def update
    solution = Solution.find(params[:id])
    solution.update(
      solution_params
    )
    # redirect_to edit_solution_path params[:id]
  end

  def index
    @solutions = Solution.all
  end

  def show
    @comment = Comment.create({body:params[:body]})
    @solution = Solution.find(params[:id])
    @challenge = Challenge.find(@solution.challenge_id)
    @data = getData(@challenge).to_json.html_safe
  end

  def destroy
    solution = Solution.find(params[:id])
    solution.destroy()
    redirect_to controller: 'users', action: 'show', id: @current_user.id
  end

  private

  def solution_params
    params.permit(:code, :challenge_id, :score)
  end

  def getData(challenge)
    data = challenge.test_pairs
    inputs = []
    outputs = []
    data.each{ |pair|
      if pair.integer_input_type? # if the input is meant to be a number, convert it to a float.
        input = pair.input.to_f;
      elsif pair.string_input_type? # if its meant to be a string, leave it as it is.
        input = pair.input;
      else                        # else it's meant to be an array, so split it on a pipe.
        input = pair.input.split('|');
      end
      inputs.push(input);

      if pair.output_integer? # if the input is meant to be a number, convert it to a float.
        output = pair.output.to_f;
      elsif pair.output_string? # if its meant to be a string, leave it as it is.
        output = pair.output;
      else                        # else it's meant to be an array, so split it on a pipe.
        output = pair.output.split('|');
      end
      outputs.push(output);
    };
    data = {inputs: inputs , outputs: outputs}
  end
end

app/helpers/solutions_helper.rb
module SolutionsHelper
end

app/views/solutions/_formnew.html.erb
<div class='form-container'>
  <div class='top'>
    <textarea name="definition" id="definitionArea" cols="30" rows="10">const funk = function(input){</textarea>
  </div>
  <div class='mid'>
    <%= form_for @solution, :html => {class: 'code-form'} do |f| %>
      <%= f.hidden_field :score, {value: 0, id: "scorefield" }%>
      <%= f.hidden_field :challenge_id, {value: @solution.challenge_id, id: "challenge-id"}%>
      <%= f.hidden_field :user_id, {value: @current_user.id, id: "user-id"}%>
      <%= f.text_area :code, {class: 'codearea', id: 'editor'}%>
      <div class="button-grid">
        <a href="/solutions/<%= @solution.id %>" method="delete" id="delete-button" class="btn btn-warning">Delete This Solution</a>
        <%= f.submit 'Save Solution', class: 'submit-button btn btn-primary' %>
        <a href="/solutions/<%= @solution.id %>" id="back-button" class="btn btn-warning">Stop Edit</a>
        <button type="button" name="button" class="runButton btn btn-info" onClick='RunSolution()'>Run Code</button>
      </div>
    <% end %>
  </div>
  <div class='bottom'>
    <textarea name="return" id="returnArea" cols="30" rows="10">    return output;
}</textarea>
  </div>
</div>

<script>
  $(document).ready(function(){
    convertForm();
  });
</script>

app/views/solutions/create.html.erb
<h1>Solutions#create</h1>
<p>Find me in app/views/solutions/create.html.erb</p>

app/views/solutions/destroy.html.erb
<h1>Solutions#destroy</h1>
<p>Find me in app/views/solutions/destroy.html.erb</p>

app/views/solutions/edit.html.erb
<div class="grid-Container">
  <div class="challenge-info">
    <h2><a href="/challenges/<%= @challenge.id %>"><%= @challenge.name %></a></h2>
    <p><%= @challenge.description %> <br>
      <strong>Example Input-->Output:</strong> <%= @challenge.test_pairs[0].input %> --> <%= @challenge.test_pairs[0].output %>
    </p>
  </div>
  <div class="code-textarea">
    <%= render partial: 'formnew' %>
  </div>
  <div class="results">
    <div></div>
  </div>
</div>

<script>
  $(document).ready(function(){
    data = (<%= @data %>);
    const solutionUrl = "http://localhost:3000/solutions/<%= @solution.id %>"
    $form = $('.code-form')
    $form.submit( function(event){
      event.preventDefault();
      RunSolution();
      $.ajax({
        type: 'PUT',
        url: solutionUrl,
        data: {
          challenge_id: $('#challenge-id').val(),
          score: $('#scorefield').val(),
          code: $('#editor').val()
        }
      })
      .done( response => {
        $('.results div').text("Saved Succesfully!");
      })
      .fail( console.warn )
      .always(() => {
        $('.submit-button').prop('disabled', false)
      });
    });
  });
</script>

app/views/solutions/index.html.erb
<h1>Solutions#index</h1>
<p>Find me in app/views/solutions/index.html.erb</p>

app/views/solutions/new.html.erb
<div class="grid-Container">
  <div class="challenge-info">
    <h2><%= @challenge.name %></h2>
    <p><%= @challenge.description %></p>
  </div>
  <div class="code-textarea">
    <%= render partial: 'formnew' %>
  </div>
  <div class="results">
    <button type="button" name="button" onClick='RunSolution()'>Run Code</button>
    <div></div>
  </div>
</div>

<script>
  $(document).ready(function(){
    data = (<%= @data %>);
    $form = $('.code-form')
    $form.submit( event => {
      // event.preventDefault();
      // console.log(event);
      RunSolution();
      event.target[2].value = score;
    })
  });
</script>

app/views/solutions/show.html.erb
<div class="grid-Container">
  <div class="challenge-info">
    <h2><a href="/challenges/<%= @challenge.id %>"><%= @challenge.name %></a></h2>
    <p><%= @challenge.description %> <br>
      <strong>Example Input-->Output:</strong> <%= @challenge.test_pairs[0].input %> --> <%= @challenge.test_pairs[0].output %>
    </p>
    <p><%= link_to "Start Another Challenge", challenge_path("#{Challenge.all.ids.sample}"), class:"btn btn-success" %></p>
  </div>
  <div class="code-textarea">
    <textarea name="code" class="codearea" id="editor">
let funk = function(input){
<%= @solution.code %>
return output;
}
    </textarea>
    <% if @solution.user_id == @current_user.id %>
      <a href="/solutions/<%= @solution.id %>/edit" class="editLink btn btn-primary">Edit Solution</a>
    <% end %>
  </div>
  <div class="results">
    <div class="resultAppend">
      This solution produced the correct output for <%= @solution.score %>% of the given inputs.
    </div>
  </div>
  <div class="commentSection">
    <h2>Comments</h2>
    <div class="allComments">
      <% @solution.comments.each do |comment| %>
        <div class="commentBox">
          <strong><p><%= comment.user.name %> says:</p></strong>
          <p><%= simple_format(comment.body) %></p>
          <span class="comment">created <%= time_ago_in_words(comment.created_at) %> ago</span>
          <% if @current_user.present? %>
            <% if comment.user_id == @current_user.id %>
            <span class="comment"><%= link_to 'remove', comment_path(comment.id), method: 'delete' %> </span>
            <% end %>
          <% end %>
        </div>
      <% end %>
    </div>
    <br>
    <%= form_tag(comments_path, {class: "commentsForm"}) do  %>
      leave a <%= label_tag :Comment %>: <br>
      <%= text_area_tag(:body) %> <br>
      <%= hidden_field_tag :solution_id,"#{@solution.id}" %>
      <br>
      <%= submit_tag("Post Comment", {class: "submitComment"})%>
    <% end  %>
  </div>
</div>

<script>
  $(document).ready(function(){
    data = (<%= @data %>);
  });
  myTextArea = $('.codearea')[0];
  editor = CodeMirror.fromTextArea( myTextArea, {
    value: myTextArea.value,
    theme: 'liquibyte',
    lineNumbers: true,
    readOnly: true
  });
</script>

app/views/solutions/trial.html.erb
<div class="grid-Container">
  <div class="challenge-info">
    <h2><a href="/challenges/<%= @challenge.id %>"><%= @challenge.name %></a></h2>
    <p><%= @challenge.description %> <br>
      <strong>Example Input-->Output:</strong> <%= @challenge.test_pairs[0].input %> --> <%= @challenge.test_pairs[0].output %>
    </p>
  </div>
  <div class="form-container">
    <div class='top'>
      <textarea name="definition" id="definitionArea" cols="30" rows="10">const funk = function(input){</textarea>
    </div>
    <div class='mid'>
      <textarea name="code" class="codearea" id="editor"></textarea>
    </div>
    <div class='bottom'>
      <textarea name="return" id="returnArea" cols="30" rows="10">    return output;
}</textarea>
    </div>
  </div>
  <div id="aside">
    <strong>This is the trial page. Feel free to write some code and play around, but you wont be able to save anything until you're logged into an account</strong> <br>
    <p><%= link_to "Look at other challenges", challenges_path%></p>
  </div>
  <div class="results">
    <button type="button" name="button" onClick='RunSolution()' class="runButton btn btn-info">Run Code</button>
    <div></div>
  </div>
</div>

<script>
  $(document).ready(function(){
    data = (<%= @data %>);
    let myTextArea = $('#definitionArea')[0];
    editor = CodeMirror.fromTextArea( myTextArea, {
      value: myTextArea.value,
      theme: 'liquibyte',
      lineNumbers: false,
      readOnly: true,
    });
    myTextArea = $('#returnArea')[0];
    editor = CodeMirror.fromTextArea( myTextArea, {
      value: myTextArea.value,
      theme: 'liquibyte',
      lineNumbers: false,
      readOnly: true,
    });
    myTextArea = $('.codearea')[0];
    editor = CodeMirror.fromTextArea( myTextArea, {
      value: myTextArea.value,
      theme: 'liquibyte',
      lineNumbers: true,
    });
  });
</script>

app/views/solutions/update.html.erb
<h1>Solutions#update</h1>
<p>Find me in app/views/solutions/update.html.erb</p>