config/routes.rb
Rails.application.routes.draw do
  root 'session#new'


  get 'session/new'

  get 'session/create'
  get 'session/destroy'

  get "/login" => "session#new"
  post "/login" => "session#create"
  delete "/login" => "session#destroy"

  get "/solutions/trial" => "solutions#trial"
  resources :solutions

  resources :challenges
  resources :test_pairs
  resources :users
  resources :comments
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BackendProject2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>


  <body>




    <header>







          <% if @current_user.present? %>
          <nav class=" navbar navbar-expand-lg navbar-light bg-dark">
            <div class = "navbar-brand">
              Welcome back, <%= @current_user.name %>
            </div>
            <div class="navbar-brand">
              <%= link_to 'Challenges', challenges_path , class: "navLink challenges"  %>

              <%= link_to 'Profile', user_path(@current_user.id) , class: "navLink profile"  %>
              <%= link_to 'Logout ', login_path, method: 'delete', class: "navLink logout"  %>
            </div>
          </nav>
          <% else %>
          <nav class="navbar navbar-expand-lg navbar-light bg-dark">
            <div class="navbar-brand">
              <%= link_to 'Challenges', challenges_path , class: "navLink login"  %>
              <%= link_to 'Signup', new_user_path, class: "navLink login" %>
              <%= link_to 'Login', login_path, class: "navLink login" %>
            </div>
          </nav>
          <% end %>
        </header>

      <main>
      <%= yield %>
    </main>



  </body>
</html>